name: First workflow

on:
  # Manual trigger using workflow_dispatch
  workflow_dispatch:

  # Automatic trigger on push events
  push:
    branches:
      - main

  # Automatic trigger on pull requests events
  pull_request:
    branches:
      - main

  # Schedueld trigger at 5:00 AM UTC, Mon-Fri
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Use Node.js
      uses: actions/setup-node@v4
      with: 
        node-version: latest

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Print a message
      run: echo "Hello, world!"
